name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: false

jobs:
  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./web
      # Using npm ci is generally faster than running npm i because it caches dependencies
      run: |
        npm ci
    - name: Build the app
      working-directory: ./web
      run: |
        npm run build
    - name: Run component tests
      working-directory: ./web
      run: |
        npm run test
    - name: Archive webpage
      uses: actions/upload-artifact@v4
      with:
        path: |
          web/dist/

  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: Gr1N/setup-poetry@v9
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: artifact
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
